---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
# MTH 441 Lab Assignment 2
### Viral Chitlangia


## P1

```{r}
data.File1 <- read.csv("rocket_propellant.csv")
model1 <- lm(Shear.Strength..psi. ~ Age.of.Propellant..weeks., data = data.File1)
model1$coefficients
```
## P2

```{r}
data.File2 <- read.csv("delivery_times.csv")
model2 <- lm(Delivery_Time ~ Number_of_Cases_x1 + Distance_x2, data = data.File2)
model2$coefficients
```
```{r}
X <- cbind(numeric(length(data.File1$Observation)) + 1, data.File1)
colnames(X)[1] <- "One"
X <- X[, c(1, 4)]
X <- as.matrix(X, nrow = length(X$'One'), ncol = 2)
```

## P3

```{r}
# 1
variance <- sum(model1$residuals^2)/(length(data.File1[,2]) - 2)
variance

# 2
varVec <- variance * solve(t(X) %*% X)
Var <- diag(varVec)
t <- model1$coefficients/Var
t
```
## P4

```{r}
# 1
W <- vector()
for (i in 1:5000) {
  W <- append(W, rnorm(1)^2 + rnorm(1)^2 + rnorm(1)^2)
}


# 2
hist(W)
m <- mean(W)
v <- var(W)

# 3
theoretical.mean <- 3
theoretical.variance <- 6

# 4
m - theoretical.mean
v - theoretical.variance
```
## P5
```{r}
# 1
X <- matrix(rnorm(40, 5, 3), nrow = 8, ncol = 5)
Px <- X %*% solve(t(X) %*% X) %*% t(X)
if (norm(Px - Px%*%Px, type = "2") < 1e-6) {
  print("Px is Idempotent")
}

# 2
S <- NULL
for (i in 1:5000) {
  Y <- NULL
  for (j in 1:8) {
    Y <- c(Y, rnorm(1))
  }
  Y <- as.matrix(Y, 1, 8)
  S <- c(S, t(Y) %*% Px %*% Y)
}


# 3
hist(S)
m <- mean(S)
v <- var(S)
m
v

# 4
theoretical.mean <- 5
theoretical.variance <- 10

# 5
m - theoretical.mean
v - theoretical.variance
```
## P6
```{r}

# 2
P.X.1 = Px
P.X.2 = diag(1, 8, 8) - P.X.1
df1 <- qr(P.X.2)$rank
df2 <- qr(P.X.1)$rank
S <- NULL
for (i in 1:5000) {
  Y <- NULL
  for (j in 1:8) {
    Y <- c(Y, rnorm(1))
  }
  Y <- as.matrix(Y, 1, 8)
  S <- c(S, as.vector(t(Y) %*% P.X.2 %*% Y / df1)/(t(Y) %*% P.X.1 %*% Y / df2))
}


# 3
hist(S)
m <- mean(S)
v <- var(S)
m
v

# 4
theoretical.mean <- 5/3
theoretical.variance <- (2 * (5^2) * (3 + 5 - 2)) / (3 * (5 - 2)^2 * (5 - 4))
theoretical.mean
theoretical.variance
  
# 5
m - theoretical.mean
v - theoretical.variance
```

